### ISSUE TITLE
How to obtain FL results using GZoltar 1.6.0 jar?

### ISSUE THREAD

**Issue by DehengYang** [SerVal-DTF/FL-VS-APR#1]
Hi, 

After I have read the whole project, which is really well-written and well organized, I have got a question in my mind: how to get FL results using GZoltar 1.6.0 jar.

It seems that the ways to use GZoltar 1.6.0 and 0.1.1 are quite different in this project. I mean: 

+ [x] when using GZoltar 0.1.1, the project writes java code (see GZoltarFaultLoclaization.java) to pass parameters to GZolta 0.1.1 jar.
+ [x] but while using GZoltar 1.6.0, the project seems to use parseResults() function to read files from external folders (e.g., "GZoltar-1.6.0/crushMatrixOutput/").

So I would like to ask that are the fault localization results of GZoltar 1.6.0 version obtained from command line (as opposed to Java implementation) ?

Much appreciated if any guidance can be given.

**Comment by Kui-Liu** [comment]
Hello @DehengYang, 
Yes, the results of fault localization with GZoltar 1.6.0 are indeed obtained from the command line.  We did not find an efficient way of integrating GZoltar 1.6.0 into our tool.

**Comment by DehengYang** [comment]
Thanks, this may be a future direction to develop this project. Thanks for the answer!
