### ISSUE TITLE
Question about your code FL-VS-APR

### ISSUE THREAD

**Issue by leila-you** [SerVal-DTF/FL-VS-APR#4]
Hi.
I'm a PhD student and I want to run your code but the path you use in this project confuses me. Is the data you upload in github equals to your dataset?

**Comment by Kui-Liu** [comment]
Hello, the data of those paths are equal to my used dataset.
But the dataset is the old version of Defects4J, not the latest version of Defects4J.
It seems that there are some differences between the old version and the latest version.

**Comment by leila-you** [comment]
What version of Defect4j you use?
 Please help me to run it. Can you help me  run it step by step?

در تاریخ چهارشنبه ۱۹ اوت ۲۰۲۰،‏ ۱۲:۲۰ Kui LIU <notifications@github.com>
نوشت:

**Comment by Kui-Liu** [comment]
https://github.com/rjust/defects4j/releases/tag/v1.2.0
This is the version of the used Defects4J.
If you want to the latest version of Defects4J, it is not difficult. You just need to change the related paths for each bug.
I recommend you to use an IDE (e.g., eclipse) to run it step by step in the debug way.

**Comment by leila-you** [comment]
Thank you very much.

در تاریخ پنجشنبه ۲۰ اوت ۲۰۲۰،‏ ۵:۴۹ Kui LIU <notifications@github.com> نوشت:

**Comment by leila-you** [comment]
Do you have a paper related to this project?

در تاریخ پنجشنبه ۲۰ اوت ۲۰۲۰،‏ ۹:۵۲ Leila Yousofvand <l.yousofvand@gmail.com>
نوشت:

**Comment by Kui-Liu** [comment]
@inproceedings{liu2019you,

  title={You Cannot Fix What You Cannot Find! An Investigation of Fault
Localization Bias in Benchmarking Automated Program Repair Systems},

  author={Liu, Kui and Koyuncu, Anil and Bissyand{\'e}, Tegawend{\'e} F.
and Kim, Dongsun and Klein, Jacques and Le Traon, Yves},

  booktitle={Proceedings of the 12th IEEE International Conference on
Software Testing, Verification and Validation},

  year={2019},

  pages = {102--113},

  doi={10.1109/ICST.2019.00020},

  organization={IEEE}

}
